#if UNITY_EDITOR
using System;
using System.IO;
using System.Text;
using NUnit.Framework;
using HabitatShift.Core;
using UnityEngine;

namespace HabitatShift.Tests {
public sealed class GameRulesTests {
  LevelDto Level(string constraint="FREE") { return new LevelDto { id=1, cols=6, rows=6, habitats=new[]{new HabitatDto{id="H",color="orange",anchor=new IntPair{x=0,y=0},shape=new[]{new IntPair{x=0,y=0}},need=2,movementConstraint=constraint}}, targets=new[]{new TargetDto{id="S1",color="orange",position=new FloatPair{x=2.5f,y=.5f}},new TargetDto{id="S2",color="orange",position=new FloatPair{x=3.5f,y=.5f}}}, elevators=new ElevatorDto[0], obstacles=new IntPair[0]}; }
  RulesetDto Rules()=>new RulesetDto{dragSweepStep=.08f,collectionTolerance=.12f,foreignSproutlingCollisionRadius=.18f,narrowCorridorDragCollisionInset=.1f,activeDragHabitatCollisionSkin=.04f,strictProjectionRadius=.12f,contactReleaseHysteresis=.20f,strictCorrectionPerSweep=.02f,contactSolverIterations=4};
  static byte[] CatalogBytes()=>File.ReadAllBytes(Path.Combine(Application.streamingAssetsPath,"HabitatShift","approved_levels_v4.json"));
  static byte[] RulesBytes()=>File.ReadAllBytes(Path.Combine(Application.streamingAssetsPath,"HabitatShift","ruleset_manifest_v1.json"));

  [Test] public void CatalogPayload_ValidProductionBytes_DeserializeAndValidate(){RulesetDto rules;var catalog=CatalogLoader.LoadFromBytes(CatalogBytes(),RulesBytes(),out rules);Assert.NotNull(catalog);Assert.NotNull(rules);Assert.AreEqual(23,catalog.levelCount);Assert.AreEqual("continuous-core-v2",rules.rulesetVersion);}
  [Test] public void CatalogPayload_ChangedCatalogByte_FailsSha(){var bytes=CatalogBytes();bytes[0]^=1;Assert.Throws<InvalidOperationException>(()=>{RulesetDto rules;CatalogLoader.LoadFromBytes(bytes,RulesBytes(),out rules);});}
  [Test] public void CatalogPayload_ChangedRulesByte_FailsSha(){var bytes=RulesBytes();bytes[0]^=1;Assert.Throws<InvalidOperationException>(()=>{RulesetDto rules;CatalogLoader.LoadFromBytes(CatalogBytes(),bytes,out rules);});}
  [Test] public void CatalogPayload_EmptyPayload_Fails(){Assert.Throws<InvalidOperationException>(()=>{RulesetDto rules;CatalogLoader.LoadFromBytes(Array.Empty<byte>(),RulesBytes(),out rules);});}
  [Test] public void CatalogPayload_InvalidJson_FailsWithoutFilesystem(){Assert.Throws<InvalidOperationException>(()=>{RulesetDto rules;CatalogLoader.DeserializeValidatedPayloads(Encoding.UTF8.GetBytes("{broken"),RulesBytes(),out rules);});}
  [Test] public void CatalogPayload_InvalidIdentity_FailsWithoutFilesystem(){var raw=Encoding.UTF8.GetString(CatalogBytes()).Replace("m7-20260928-levels-19-23","invalid-revision");Assert.Throws<InvalidOperationException>(()=>{RulesetDto rules;CatalogLoader.DeserializeValidatedPayloads(Encoding.UTF8.GetBytes(raw),RulesBytes(),out rules);});}
  [Test] public void CatalogPayload_ExpandedCatalog_HasLevels19To23(){RulesetDto rules;var catalog=CatalogLoader.LoadFromBytes(CatalogBytes(),RulesBytes(),out rules);Assert.AreEqual(23,catalog.levelCount);Assert.AreEqual(23,catalog.levels.Length);for(var i=0;i<catalog.levels.Length;i++){var level=catalog.levels[i];Assert.AreEqual(i+1,level.id);Assert.IsNotNull(level.habitats);Assert.IsNotNull(level.targets);Assert.IsNotNull(level.elevators);}Assert.AreEqual(11,catalog.levels[18].habitats.Length);Assert.AreEqual(2,catalog.levels[18].elevators.Length);Assert.AreEqual(10,catalog.levels[19].habitats.Length);Assert.AreEqual(8,catalog.levels[20].habitats.Length);Assert.AreEqual(4,catalog.levels[20].elevators.Length);Assert.AreEqual(11,catalog.levels[21].habitats.Length);Assert.AreEqual(10,catalog.levels[22].habitats.Length);Assert.AreEqual(1,catalog.levels[22].elevators.Length);Assert.IsTrue(System.Array.Exists(catalog.levels[18].habitats,habitat=>habitat.color=="white"));}

  [Test] public void ContinuousDrag_CollectsAndCommitsOneMove(){var s=new ContinuousSession(Level(),Rules());Assert.True(s.BeginDrag("H",new Vector2(.5f,.5f)));s.MovePointer(new Vector2(3.5f,.5f));Assert.True(s.EndDrag());Assert.AreEqual(1,s.Committed.moves);Assert.True(s.Committed.won);}
  [Test] public void Constraint_FiltersForbiddenAxis(){var s=new ContinuousSession(Level("HORIZONTAL_ONLY"),Rules());s.BeginDrag("H",new Vector2(.5f,.5f));s.MovePointer(new Vector2(.5f,3.5f));s.EndDrag();Assert.AreEqual(0f,s.Committed.habitats[0].anchor.y);}
  [Test] public void Undo_RestoresCommittedState(){var s=new ContinuousSession(Level(),Rules());s.BeginDrag("H",new Vector2(.5f,.5f));s.MovePointer(new Vector2(2.5f,.5f));s.EndDrag();Assert.True(s.Undo());Assert.AreEqual(0,s.Committed.moves);Assert.AreEqual(2,s.Committed.sprouts.Count);}
  [Test] public void GardenShift_ConsumesOneTarget(){var s=new ContinuousSession(Level(),Rules());Assert.True(s.UseAssist(AssistKind.GardenShift,"H","S1",Vector2Int.zero));Assert.AreEqual(1,s.Committed.sprouts.Count);}
  [Test] public void NestBloom_CollectsAllRequiredBoardTargets(){var s=new ContinuousSession(Level(),Rules());Assert.True(s.UseAssist(AssistKind.NestBloom,"H","",Vector2Int.zero));Assert.AreEqual(0,s.Committed.sprouts.Count);Assert.AreEqual(0,s.Committed.habitats.Count);}
  [Test] public void NestBloom_RejectsMatchingElevatorQueue(){var l=Level();l.elevators=new[]{new ElevatorDto{id="E",direction="RIGHT",entry=new FloatPair{x=5.5f,y=5.5f},queue=new[]{new QueueItemDto{id="Q",color="orange"}},nextIndex=0,mandatory=true}};var s=new ContinuousSession(l,Rules());Assert.False(s.UseAssist(AssistKind.NestBloom,"H","",Vector2Int.zero));Assert.AreEqual(2,s.Committed.sprouts.Count);}
  [Test] public void RootTrim_ReducesToOriginAndRestartRestoresShape(){var l=Level();l.habitats[0].shape=new[]{new IntPair{x=0,y=0},new IntPair{x=1,y=0}};var s=new ContinuousSession(l,Rules());Assert.True(s.UseAssist(AssistKind.RootTrim,"H","",Vector2Int.zero));CollectionAssert.AreEqual(new[]{Vector2Int.zero},s.Committed.habitats[0].shape);s.Restart();Assert.AreEqual(2,s.Committed.habitats[0].shape.Count);}
  [Test] public void RootTrim_KeepsAnchorWhenOriginCornerOccupied(){var l=Level();l.targets=new TargetDto[0];l.habitats[0].shape=new[]{new IntPair{x=0,y=0},new IntPair{x=1,y=0}};var s=new ContinuousSession(l,Rules());Assert.True(s.UseAssist(AssistKind.RootTrim,"H","",Vector2Int.zero));Assert.AreEqual(Vector2.zero,s.Committed.habitats[0].anchor);Assert.AreEqual(1,s.Committed.habitats[0].shape.Count);}
  [Test] public void RootTrim_TrimsToTopLeftOccupiedCell_WhenAnchorCornerIsEmpty(){var l=Level();l.targets=new TargetDto[0];l.habitats[0].anchor=new IntPair{x=2,y=2};l.habitats[0].shape=new[]{new IntPair{x=0,y=1},new IntPair{x=1,y=0},new IntPair{x=1,y=1}};l.habitats[0].need=2;var s=new ContinuousSession(l,Rules());Assert.True(s.CanUseAssist(AssistKind.RootTrim,"H","",out var reason));Assert.True(s.UseAssist(AssistKind.RootTrim,"H","",Vector2Int.zero));CollectionAssert.AreEqual(new[]{Vector2Int.zero},s.Committed.habitats[0].shape);Assert.AreEqual(new Vector2(3,2),s.Committed.habitats[0].anchor);}
  LevelDto WallLevel(){var l=Level();l.targets=new TargetDto[0];l.obstacles=new[]{new IntPair{x=2,y=0},new IntPair{x=2,y=1},new IntPair{x=2,y=2},new IntPair{x=2,y=3},new IntPair{x=2,y=4}};return l;}
  [Test] public void DragAgainstWall_SlidesAlongOpenTangent(){var s=new ContinuousSession(WallLevel(),Rules());Assert.True(s.BeginDrag("H",new Vector2(.5f,.5f)));s.MovePointer(new Vector2(3.5f,3.5f));Assert.LessOrEqual(s.ResolvedPose.x,1.001f);Assert.Greater(s.ResolvedPose.y,2.8f);}
  [Test] public void DragAfterWallContact_ReversesWithoutPullback(){var s=new ContinuousSession(WallLevel(),Rules());s.BeginDrag("H",new Vector2(.5f,.5f));s.MovePointer(new Vector2(3.5f,3.5f));var contacted=s.ResolvedPose.x;s.MovePointer(new Vector2(.25f,3.5f));Assert.Less(s.ResolvedPose.x,contacted-.2f);}
  [Test] public void ExactWidthCorridor_ProjectsMinorLateralDrift(){var l=Level();l.cols=3;l.rows=6;l.targets=new TargetDto[0];l.habitats[0].anchor=new IntPair{x=1,y=0};l.playableMask=new[]{new IntPair{x=1,y=0},new IntPair{x=1,y=1},new IntPair{x=1,y=2},new IntPair{x=1,y=3},new IntPair{x=1,y=4},new IntPair{x=1,y=5}};var s=new ContinuousSession(l,Rules());s.BeginDrag("H",new Vector2(1.5f,.5f));s.MovePointer(new Vector2(1.57f,4.5f));Assert.AreEqual(1f,s.ResolvedPose.x,.001f);Assert.Greater(s.ResolvedPose.y,3.8f);}
  [Test] public void NarrowGap_DoesNotPermitOverlap(){var l=Level();l.targets=new TargetDto[0];l.habitats=new[]{l.habitats[0],new HabitatDto{id="BLOCK",color="blue",anchor=new IntPair{x=2,y=0},shape=new[]{new IntPair{x=0,y=0}},need=1,movementConstraint="FREE"}};var s=new ContinuousSession(l,Rules());s.BeginDrag("H",new Vector2(.5f,.5f));s.MovePointer(new Vector2(2.49f,.5f));Assert.Less(s.ResolvedPose.x,1.06f);}
  [Test] public void Restart_ClearsDragContactAndRestoresAuthoredPose(){var s=new ContinuousSession(WallLevel(),Rules());s.BeginDrag("H",new Vector2(.5f,.5f));s.MovePointer(new Vector2(3.5f,3.5f));s.EndDrag();s.Restart();Assert.AreEqual(0f,s.Committed.habitats[0].anchor.x);Assert.AreEqual(0f,s.Committed.habitats[0].anchor.y);Assert.False(s.IsDragging);}
  [Test] public void CollectionEvent_CarriesColorAndIntakeDestination(){var s=new ContinuousSession(Level(),Rules());s.BeginDrag("H",new Vector2(.5f,.5f));s.MovePointer(new Vector2(2.5f,.5f));var e=s.Events.Find(x=>x.kind==PresentationKind.Collection);Assert.NotNull(e);Assert.AreEqual("orange",e.color);Assert.Greater(e.targetPosition.x,0f);Assert.LessOrEqual(e.targetPosition.x,2.5f);Assert.AreEqual(.5f,e.targetPosition.y,.001f);}
  [Test] public void CaptureCoverage_RequiresMoreThanTwoThirds(){var s=new ContinuousSession(Level(),Rules());var h=s.Committed.habitats[0];h.anchor=new Vector2(-.397f,0f);Assert.LessOrEqual(ContinuousSession.CaptureCoverage(h,new Vector2(.5f,.5f)),ContinuousSession.CaptureThreshold);h.anchor=new Vector2(-.395f,0f);Assert.Greater(ContinuousSession.CaptureCoverage(h,new Vector2(.5f,.5f)),ContinuousSession.CaptureThreshold);}
  [Test] public void CaptureCoverage_UsesUnionOfPolyominoCells(){var s=new ContinuousSession(Level(),Rules());var h=s.Committed.habitats[0];h.shape=new System.Collections.Generic.List<Vector2Int>{new Vector2Int(0,0),new Vector2Int(1,0),new Vector2Int(0,1)};h.anchor=Vector2.zero;var coverage=ContinuousSession.CaptureCoverage(h,new Vector2(.82f,.5f));Assert.Greater(coverage,0f);Assert.LessOrEqual(coverage,1f);}

  LevelDto SettleLevel(string constraint="FREE"){var level=Level(constraint);level.targets=new TargetDto[0];level.obstacles=new IntPair[0];return level;}
  ContinuousSession BeginAt(LevelDto level,Vector2 release){var session=new ContinuousSession(level,Rules());Assert.True(session.BeginDrag("H",new Vector2(.5f,.5f)));session.Preview.habitats.Find(h=>h.id=="H").anchor=release;return session;}
  static void AssertInteger(Vector2 anchor){Assert.AreEqual(Mathf.Round(anchor.x),anchor.x,.000001f);Assert.AreEqual(Mathf.Round(anchor.y),anchor.y,.000001f);}

  [Test] public void Settle_BasicNearestIntegerAnchor(){var s=BeginAt(SettleLevel(),new Vector2(2.20f,3.20f));Assert.True(s.EndDrag());var anchor=s.Committed.habitats[0].anchor;Assert.AreEqual(new Vector2(2,3),anchor);AssertInteger(anchor);}
  [Test] public void Settle_ChoosesEuclideanNearestInsteadOfLegacyScanOrder(){var level=SettleLevel();level.obstacles=new[]{new IntPair{x=2,y=3}};var s=BeginAt(level,new Vector2(2.20f,3.20f));Assert.True(s.EndDrag());Assert.AreEqual(new Vector2(3,3),s.Committed.habitats[0].anchor);}
  [Test] public void Settle_SuccessAlwaysCommitsIntegerAnchor(){var s=BeginAt(SettleLevel(),new Vector2(2.31f,3.72f));Assert.True(s.EndDrag());AssertInteger(s.Committed.habitats[0].anchor);}
  [Test] public void Settle_RejectsCandidateAllowedOnlyByActiveDragSkin(){var level=SettleLevel();level.habitats=new[]{level.habitats[0],new HabitatDto{id="OTHER",color="blue",anchor=new IntPair{x=0,y=0},shape=new[]{new IntPair{x=0,y=0}},need=1,movementConstraint="FREE"}};var s=BeginAt(level,new Vector2(.02f,0f));s.Preview.habitats.Find(h=>h.id=="OTHER").anchor=new Vector2(.98f,0f);Assert.True(s.EndDrag());Assert.AreNotEqual(Vector2.zero,s.Committed.habitats.Find(h=>h.id=="H").anchor);}
  [Test] public void Settle_RejectsObstacleAtNearestInteger(){var level=SettleLevel();level.obstacles=new[]{new IntPair{x=2,y=3}};var s=BeginAt(level,new Vector2(2.20f,3.20f));Assert.True(s.EndDrag());Assert.AreNotEqual(new Vector2(2,3),s.Committed.habitats[0].anchor);}
  [Test] public void Settle_RejectsNearestIntegerOutsidePlayableMask(){var level=SettleLevel();level.playableMask=new[]{new IntPair{x=0,y=0},new IntPair{x=3,y=3},new IntPair{x=2,y=4},new IntPair{x=3,y=4}};var s=BeginAt(level,new Vector2(2.20f,3.20f));Assert.True(s.EndDrag());Assert.AreEqual(new Vector2(3,3),s.Committed.habitats[0].anchor);}
  [Test] public void Settle_RejectsForeignSproutlingAtNearestInteger(){var level=SettleLevel();level.targets=new[]{new TargetDto{id="FOREIGN",color="blue",position=new FloatPair{x=2.5f,y=3.5f}}};var s=BeginAt(level,new Vector2(2.20f,3.20f));Assert.True(s.EndDrag());Assert.AreEqual(new Vector2(3,3),s.Committed.habitats[0].anchor);}
  [Test] public void Settle_HorizontalOnlyKeepsCommittedRow(){var level=SettleLevel("HORIZONTAL_ONLY");level.habitats[0].anchor=new IntPair{x=0,y=1};level.obstacles=new[]{new IntPair{x=4,y=1},new IntPair{x=5,y=1}};var s=BeginAt(level,new Vector2(4.20f,1.20f));Assert.True(s.EndDrag());Assert.AreEqual(1f,s.Committed.habitats[0].anchor.y);Assert.AreEqual(3f,s.Committed.habitats[0].anchor.x);}
  [Test] public void Settle_VerticalOnlyKeepsCommittedColumn(){var level=SettleLevel("VERTICAL_ONLY");level.habitats[0].anchor=new IntPair{x=1,y=0};level.obstacles=new[]{new IntPair{x=1,y=4},new IntPair{x=1,y=5}};var s=BeginAt(level,new Vector2(1.10f,4.30f));Assert.True(s.EndDrag());Assert.AreEqual(1f,s.Committed.habitats[0].anchor.x);Assert.AreEqual(3f,s.Committed.habitats[0].anchor.y);}
  [Test] public void Settle_EqualDistanceUsesLowestYThenLowestX(){Vector2 expected=new Vector2(2,3);for(var i=0;i<5;i++){var s=BeginAt(SettleLevel(),new Vector2(2.5f,3.5f));Assert.True(s.EndDrag());Assert.AreEqual(expected,s.Committed.habitats[0].anchor);}}
  [Test] public void Settle_NoStrictIntegerCandidateFailsClosed(){var level=SettleLevel();level.cols=1;level.rows=1;level.obstacles=new[]{new IntPair{x=0,y=0}};var s=BeginAt(level,new Vector2(.31f,.42f));Assert.False(s.EndDrag());Assert.AreEqual(0,s.Committed.moves);Assert.AreEqual(Vector2.zero,s.Committed.habitats[0].anchor);AssertInteger(s.Committed.habitats[0].anchor);}
  [Test] public void Settle_UndoRestoresExactPreDragAnchor(){var s=BeginAt(SettleLevel(),new Vector2(2.20f,3.20f));Assert.True(s.EndDrag());Assert.True(s.Undo());Assert.AreEqual(Vector2.zero,s.Committed.habitats[0].anchor);Assert.AreEqual(0,s.Committed.moves);}
}}
#endif
